### ISSUE TITLE
Getting Error: Unable to initialize GTK+, is DISPLAY set properly?

### ISSUE THREAD

**Issue by mauromorales** [hidakatsuya/setup-diff-pdf#22]
I was trying this action together with pdf_matcher-testing gem and RSpec. The test passes locally but when run on GitHub Actions they fail. I'm seeing the following error, is there a way to address it?

```
Unable to init server: Could not connect: Connection refused
09:31:40: Error: Unable to initialize GTK+, is DISPLAY set properly?
```

**Comment by mauromorales** [comment]
I somehow missed the github action you already created 🤦  , switched to it and it works very well, sorry for the inconvenience

**Comment by hidakatsuya** [comment]
@mauromorales 
The reason why you see that message is that diff-pdf requires Graphical Display, but the Display server is not running in the default state of ubuntu in GitHub Actions.

However, as you said, diff-pdf will work correctly even without Display server.

You can create a virtual Display server using `xvfb-run` and run diff-pdf as follows to avoid displaying the message.
https://github.com/hidakatsuya/setup-diff-pdf/commit/c9b274008265f7ea04925732ff0b3b495c946b8f

```
xvfb-run --auto-servernum diff-pdf (or any command that involves running diff-pdf)
```

Note that xvfb-run seems to be available by default in the ubuntu environment of GitHub Actions.

**Comment by mauromorales** [comment]
@hidakatsuya thanks a lot for the explanation :) and for all this work, it has been super useful to keep automating our setup
